from __future__ import annotations

import argparse

from .model import CausalLMScorer


def main() -> None:
    parser = argparse.ArgumentParser(description="Rank existing Rime candidates with a Chinese causal LM.")
    parser.add_argument("--context", required=True, help="Committed Chinese context before the current candidate")
    parser.add_argument("--pinyin", default="", help="Current pinyin; kept for experiment metadata")
    parser.add_argument("--mode", choices=["conditional", "context_gain"], default="context_gain")
    parser.add_argument("candidates", nargs="+", help="Candidate strings already generated by Rime")
    args = parser.parse_args()

    scorer = CausalLMScorer()
    ranked = scorer.rank(args.context, args.candidates, mode=args.mode)

    print(f"model:   {scorer.model_name}")
    print(f"context: {args.context}")
    print(f"pinyin:  {args.pinyin}")
    print(f"mode:    {args.mode}\n")

    for index, item in enumerate(ranked, start=1):
        selected_score = (
            item.context_gain if args.mode == "context_gain" else item.conditional_avg_logprob
        )
        print(
            f"{index:2d}. {item.candidate:<12} score={selected_score: .4f}  "
            f"cond={item.conditional_avg_logprob: .4f}  "
            f"prior={item.prior_avg_logprob: .4f}  gain={item.context_gain: .4f}"
        )


if __name__ == "__main__":
    main()
